In [1]:
print("hello world")

hello world


In [2]:
with open('input.txt', 'r', encoding='utf-8') as f:
  raw_training_data = f.read()

print(len(raw_training_data))

1115394


In [3]:
len(set(raw_training_data))

65

In [4]:
''.join(sorted(set(raw_training_data)))

"\n !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"

In [5]:
from collections import defaultdict

freqs = defaultdict(int)

for letter in raw_training_data:
  freqs[letter] += 1

freqs

defaultdict(int,
            {'F': 1797,
             'i': 45537,
             'r': 48889,
             's': 49696,
             't': 67009,
             ' ': 169892,
             'C': 3820,
             'z': 356,
             'e': 94611,
             'n': 48529,
             ':': 10316,
             '\n': 40000,
             'B': 2761,
             'f': 15770,
             'o': 65798,
             'w': 17585,
             'p': 10808,
             'c': 15623,
             'd': 31358,
             'a': 55507,
             'y': 20448,
             'u': 26584,
             'h': 51310,
             ',': 19846,
             'm': 22243,
             'k': 7088,
             '.': 7885,
             'A': 7819,
             'l': 33339,
             'S': 4523,
             'Y': 1718,
             'v': 7793,
             '?': 2462,
             'R': 4869,
             'M': 2840,
             'W': 3530,
             "'": 6187,
             'L': 3876,
             'I': 11832,
             'N': 5079,

In [6]:
import random

SAMPLE_SIZE = 500
training_data_size = len(raw_training_data)
start = random.randrange(0, training_data_size - SAMPLE_SIZE)
print(raw_training_data[start:start+SAMPLE_SIZE])

ear with me; I am hungry for revenge,
And now I cloy me with beholding it.
Thy Edward he is dead, that stabb'd my Edward:
Thy other Edward dead, to quit my Edward;
Young York he is but boot, because both they
Match not the high perfection of my loss:
Thy Clarence he is dead that kill'd my Edward;
And the beholders of this tragic play,
The adulterate Hastings, Rivers, Vaughan, Grey,
Untimely smother'd in their dusky graves.
Richard yet lives, hell's black intelligencer,
Only reserved their factor


In [7]:
tokens = ''.join(sorted(set(raw_training_data)))
token_to_number = {t: i for i, t in enumerate(tokens)}
token_to_number

{'\n': 0,
 ' ': 1,
 '!': 2,
 '$': 3,
 '&': 4,
 "'": 5,
 ',': 6,
 '-': 7,
 '.': 8,
 '3': 9,
 ':': 10,
 ';': 11,
 '?': 12,
 'A': 13,
 'B': 14,
 'C': 15,
 'D': 16,
 'E': 17,
 'F': 18,
 'G': 19,
 'H': 20,
 'I': 21,
 'J': 22,
 'K': 23,
 'L': 24,
 'M': 25,
 'N': 26,
 'O': 27,
 'P': 28,
 'Q': 29,
 'R': 30,
 'S': 31,
 'T': 32,
 'U': 33,
 'V': 34,
 'W': 35,
 'X': 36,
 'Y': 37,
 'Z': 38,
 'a': 39,
 'b': 40,
 'c': 41,
 'd': 42,
 'e': 43,
 'f': 44,
 'g': 45,
 'h': 46,
 'i': 47,
 'j': 48,
 'k': 49,
 'l': 50,
 'm': 51,
 'n': 52,
 'o': 53,
 'p': 54,
 'q': 55,
 'r': 56,
 's': 57,
 't': 58,
 'u': 59,
 'v': 60,
 'w': 61,
 'x': 62,
 'y': 63,
 'z': 64}

In [8]:
number_to_token = {i: t for i, t in enumerate(tokens)}
number_to_token

{0: '\n',
 1: ' ',
 2: '!',
 3: '$',
 4: '&',
 5: "'",
 6: ',',
 7: '-',
 8: '.',
 9: '3',
 10: ':',
 11: ';',
 12: '?',
 13: 'A',
 14: 'B',
 15: 'C',
 16: 'D',
 17: 'E',
 18: 'F',
 19: 'G',
 20: 'H',
 21: 'I',
 22: 'J',
 23: 'K',
 24: 'L',
 25: 'M',
 26: 'N',
 27: 'O',
 28: 'P',
 29: 'Q',
 30: 'R',
 31: 'S',
 32: 'T',
 33: 'U',
 34: 'V',
 35: 'W',
 36: 'X',
 37: 'Y',
 38: 'Z',
 39: 'a',
 40: 'b',
 41: 'c',
 42: 'd',
 43: 'e',
 44: 'f',
 45: 'g',
 46: 'h',
 47: 'i',
 48: 'j',
 49: 'k',
 50: 'l',
 51: 'm',
 52: 'n',
 53: 'o',
 54: 'p',
 55: 'q',
 56: 'r',
 57: 's',
 58: 't',
 59: 'u',
 60: 'v',
 61: 'w',
 62: 'x',
 63: 'y',
 64: 'z'}

In [9]:
def encode(s):
  return_value = []
  for character in s:
    return_value.append(token_to_number[character])
  return return_value

encode("Tech Exchange")

[32, 43, 41, 46, 1, 17, 62, 41, 46, 39, 52, 45, 43]

In [10]:
def decode(nums):
  return ''.join([number_to_token[n] for n in nums])

decode(encode("Tech Exchange"))

'Tech Exchange'

In [11]:
import torch

# data = torch.tensor(encode(raw_training_data), dtype=torch.long)

data = torch.tensor(encode(raw_training_data), dtype=torch.long)

In [12]:
holdout_size = int(0.1 * len(data))
holdout_size

111539

In [13]:
test_data = data[:holdout_size]
training_data = data[holdout_size:]
len(test_data), len(training_data)

(111539, 1003855)

In [14]:
BLOCK_SIZE = 8
training_data[:BLOCK_SIZE+1]

tensor([43, 58,  6,  1, 25, 39, 56, 41, 47])

In [15]:
start_from = random.randint(0, training_data_size-BLOCK_SIZE)
decode(training_data[start_from:start_from+BLOCK_SIZE].tolist())

't days,\n'

In [16]:
random.seed(3434)
start_from = random.randint(0, training_data_size-BLOCK_SIZE)
decode(training_data[start_from:start_from+BLOCK_SIZE].tolist())

'like asi'

In [17]:
x = training_data[:BLOCK_SIZE]
y = training_data[1:BLOCK_SIZE+1]
for t in range(BLOCK_SIZE):
    context = x[:t+1]
    target = y[t]
    print(f'in: {context}, out: {target}')

in: tensor([43]), out: 58
in: tensor([43, 58]), out: 6
in: tensor([43, 58,  6]), out: 1
in: tensor([43, 58,  6,  1]), out: 25
in: tensor([43, 58,  6,  1, 25]), out: 39
in: tensor([43, 58,  6,  1, 25, 39]), out: 56
in: tensor([43, 58,  6,  1, 25, 39, 56]), out: 41
in: tensor([43, 58,  6,  1, 25, 39, 56, 41]), out: 47


In [18]:
torch.manual_seed(1337)

BATCH_SIZE = 4

In [26]:
def get_batch(split):
  data = training_data if split == 'train' else test_data
  ix = torch.randint(len(data) - BLOCK_SIZE, (BATCH_SIZE,))
  #print(ix)
  x = torch.stack([data[i:i+BLOCK_SIZE] for i in ix])
  y = torch.stack([data[i+1:i+BLOCK_SIZE+1] for i in ix])
  return x, y

get_batch('train')
     

(tensor([[46, 43,  1, 54, 56, 47, 57, 53],
         [59, 45, 46, 47, 52, 45,  1, 47],
         [61, 43,  1, 46, 43, 52, 41, 43],
         [42, 61, 39, 56, 42,  6,  0, 13]]),
 tensor([[43,  1, 54, 56, 47, 57, 53, 52],
         [45, 46, 47, 52, 45,  1, 47, 52],
         [43,  1, 46, 43, 52, 41, 43,  1],
         [61, 39, 56, 42,  6,  0, 13, 57]]))

In [27]:
xb, yb = get_batch('train')

for b in range(BATCH_SIZE):
  for t in range(BLOCK_SIZE):
    context = xb[b, :t+1]
    target = yb[b,t]
    print(f'input {context.tolist()}, target {target}')

input [52], target 53
input [52, 53], target 58
input [52, 53, 58], target 1
input [52, 53, 58, 1], target 42
input [52, 53, 58, 1, 42], target 53
input [52, 53, 58, 1, 42, 53], target 5
input [52, 53, 58, 1, 42, 53, 5], target 58
input [52, 53, 58, 1, 42, 53, 5, 58], target 8
input [1], target 35
input [1, 35], target 43
input [1, 35, 43], target 57
input [1, 35, 43, 57], target 58
input [1, 35, 43, 57, 58], target 51
input [1, 35, 43, 57, 58, 51], target 53
input [1, 35, 43, 57, 58, 51, 53], target 56
input [1, 35, 43, 57, 58, 51, 53, 56], target 43
input [39], target 56
input [39, 56], target 58
input [39, 56, 58], target 46
input [39, 56, 58, 46], target 11
input [39, 56, 58, 46, 11], target 0
input [39, 56, 58, 46, 11, 0], target 28
input [39, 56, 58, 46, 11, 0, 28], target 56
input [39, 56, 58, 46, 11, 0, 28, 56], target 43
input [63], target 43
input [63, 43], target 56
input [63, 43, 56], target 1
input [63, 43, 56, 1], target 53
input [63, 43, 56, 1, 53], target 59
input [63, 

In [21]:
import torch
import torch.nn as nn
from torch.nn import functional as F

In [55]:
BATCH_SIZE = 32
BLOCK_SIZE = 32
LEARNING_RATE = 1e-3
MAX_ITERS = 5000
EVAL_INTERVAL = 300
EVAL_ITERS = 200
NUM_EMBEDDINGS = 32

In [50]:
vocab_size = len(set(raw_training_data))

class Head(nn.Module):
  def __init__(self, head_size):
    super().__init__()
    self.key = nn.Linear(NUM_EMBEDDINGS, head_size, bias=False)
    self.query = nn.Linear(NUM_EMBEDDINGS, head_size, bias=False)
    self.value = nn.Linear(NUM_EMBEDDINGS, head_size, bias=False)
    self.register_buffer('tril', torch.tril(torch.ones(BLOCK_SIZE, BLOCK_SIZE)))

  def forward(self, x):
    B,T,C = x.shape
    k = self.key(x)
    q = self.query(x)
    wei = q @ k.transpose(-2, -1) * C**-0.5
    wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf'))
    wei = F.softmax(wei, dim=-1)
    v = self.value(x)
    out = wei @ v
    return out

class MultiHeadAttention(nn.Module):
    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])

    def forward(self, x):
        return torch.cat([h(x) for h in self.heads], dim=-1)

class BigramLanguageModel(nn.Module):

  def __init__(self, vocab_size):
    super().__init__()
    self.token_embedding_table = nn.Embedding(vocab_size, NUM_EMBEDDINGS)
    self.position_embedding_table = nn.Embedding(BLOCK_SIZE, NUM_EMBEDDINGS)
    #self.sa_head = Head(NUM_EMBEDDINGS)
    self.sa_heads = MultiHeadAttention(4, NUM_EMBEDDINGS//4)
    self.lm_head = nn.Linear(NUM_EMBEDDINGS, vocab_size)


  def forward(self, token, targets=None):
    token_embeddings = self.token_embedding_table(token)
    B, T = token.shape
    position_embeddings = self.position_embedding_table(torch.arange(T))
    x = token_embeddings + position_embeddings

    x = self.sa_heads(x)
    logits = self.lm_head(x)

    if targets is None:
      loss = None
    else:
      B, T, C = logits.shape
      logits = logits.view(B*T, C)
      targets = targets.view(B*T)
      loss = F.cross_entropy(logits, targets)

    return logits, loss

  def generate(self, idx, max_new_tokens):
    for _ in range(max_new_tokens):
      idx_cond = idx[:, -BLOCK_SIZE:]
      logits, loss = self(idx_cond)
      logits = logits[:, -1, :] # (B, C)
      probs = F.softmax(logits, dim=-1) # (B, C)
      idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
      idx = torch.cat((idx, idx_next), dim=1)
    return idx

m = BigramLanguageModel(vocab_size)
z = torch.zeros((1,1), dtype=torch.long)
print(decode(m.generate(z, 40)[0].tolist()))
     


x?vdKvEpMXON B.uDt-WMeOXlMe.wqjkk;ffNfGh


In [51]:
@torch.no_grad()
def estimate_loss():
  out = {}
  m.eval()
  for split in ['train', 'val']:
    losses = torch.zeros(EVAL_ITERS)
    for k in range(EVAL_ITERS):
      X, Y = get_batch(split)
      logits, loss = m(X, Y)
      losses[k] = loss.item()
    out[split] = losses.mean()
  m.train()
  return out

In [52]:
optimizer = torch.optim.Adam(m.parameters(), lr=1e-3)

for iter in range(MAX_ITERS):

  if iter % EVAL_INTERVAL == 0:
    losses = estimate_loss()
    print(f"iter {iter}; train loss {losses['train']:.4f}; val loss {losses['val']:.4f}")

  xb, yb = get_batch('train')

  logits, loss = m(xb, yb)
  optimizer.zero_grad(set_to_none=True)
  loss.backward()
  optimizer.step()

iter 0; train loss 4.2278; val loss 4.2309
iter 300; train loss 2.8054; val loss 2.8098
iter 600; train loss 2.6022; val loss 2.5881
iter 900; train loss 2.5053; val loss 2.4983
iter 1200; train loss 2.4609; val loss 2.4623
iter 1500; train loss 2.4177; val loss 2.4298
iter 1800; train loss 2.3950; val loss 2.4106
iter 2100; train loss 2.3674; val loss 2.3906
iter 2400; train loss 2.3538; val loss 2.3771
iter 2700; train loss 2.3290; val loss 2.3524
iter 3000; train loss 2.3150; val loss 2.3394
iter 3300; train loss 2.3087; val loss 2.3504
iter 3600; train loss 2.2898; val loss 2.3350
iter 3900; train loss 2.2903; val loss 2.3105
iter 4200; train loss 2.2718; val loss 2.3119
iter 4500; train loss 2.2795; val loss 2.2974
iter 4800; train loss 2.2575; val loss 2.2954


In [47]:
list(sorted(set(raw_training_data)))[25]

'M'

In [56]:
z = torch.zeros((1,1), dtype=torch.long)
generated = m.generate(z, max_new_tokens=100000)
generated_list = generated[0].tolist()
print(decode(generated_list))

IndexError: index out of range in self

In [53]:
torch.tril(torch.ones(3,3))

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])